#!/usr/bin/env bash
# script that displays Best School 10 times using a while loop
# and hi 0n 9th iteration

n=1;
while [ $n -le 10 ];
do
    echo "Best School"
    (( n++ ))
    if [ $n -eq 10 ]
    then
        echo "Hi"
    fi
done

exit 0
